[build]
  publish = "public"
  command = "npm run build"
  functions = "functions"

[build.environment]
  NODE_VERSION = "10"

[[headers]]
  for = "/*"
  [headers.values]
    Strict-Transport-Security = "max-age=63072000; includeSubDomains; preload"
    # Content-Security-Policy = "default-src data: 'unsafe-inline' 'unsafe-eval' https:; script-src data: 'unsafe-inline' 'unsafe-eval' https: blob:; style-src data: 'unsafe-inline' https:; img-src data: https: blob:; font-src data: https:; connect-src https: wss: blob:; media-src https: blob:; object-src https:; child-src https: data: blob:; form-action https:; block-all-mixed-content"
    # Content-Security-Policy = "default-src 'self'"
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "no-referrer"
    Feature-Policy = "microphone 'none'; geolocation 'none'"

[[plugins]]
  package = "@netlify/plugin-lighthouse"
 
  # optional, fails build when a category is below a threshold
  [plugins.inputs.thresholds]
    performance = 0.8
    accessibility = 0.9
    best-practices = 0.9
    seo = 0.9
    pwa = 0.9

  [[plugins.inputs.audits]]
    path = "posts"

    [plugins.inputs.audits.thresholds]
      performance = 0.9

  [[plugins.inputs.audits]]
    path = "about-me"

    [plugins.inputs.audits.thresholds]
      performance = 0.9

  [[plugins.inputs.audits]]
    path = "contact-me"

    [plugins.inputs.audits.thresholds]
      performance = 0.9

  [[plugins.inputs.audits]]
    path = "todos"

    [plugins.inputs.audits.thresholds]
      performance = 0.9