backend:
  name: github
  repo: jameskolean/gatsby-jameskolean-tech
media_folder: static/assets
public_folder: /assets
# publish_mode: editorial_workflow
collections:
  - name: post
    label: Post
    folder: _data/post
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    create: true
    fields:
      - { label: Template, name: template, widget: hidden, default: BlogPost }
      - { name: date, label: Date, widget: datetime }
      - { name: published, label: Published, widget: 'boolean', default: false }
      - { name: title, label: Title }
      - { name: source, label: Source, required: false }
      - label: 'Tags'
        name: 'tags'
        widget: 'relation'
        collection: 'tag'
        displayFields: ['title']
        searchFields: ['title']
        valueField: 'title'
        multiple: true
        required: false
      - label: Featured Image
        name: thumbnail
        widget: image
        hint: 'Image size 1280x800 works best :)'
        required: false
        media_library:
          config:
            multiple: false
      - { name: body, label: Body, widget: markdown }
  - label: Tag
    name: tag
    folder: _data/tags
    slug: '{{slug}}'
    create: true
    fields:
      - { label: Template, name: template, widget: hidden, default: Tag }
      - { label: Title, name: title, widget: string }
  - label: Todo Page
    name: todoPage
    folder: _data/pages/todo
    create: false
    fields:
      - { label: Template, name: template, widget: hidden, default: TodoPage }
      - { label: Title, name: title, widget: string }
      - label: Todos
        name: todos
        widget: list
        fields:
          - { label: Name, name: name, widget: string }
          - {
              label: Decsription,
              name: description,
              widget: text,
              required: false,
            }
  - label: Index Page
    name: indexPage
    folder: _data/pages/index
    create: false
    fields:
      - { label: Template, name: template, widget: hidden, default: IndexPage }
      - { label: Title, name: title, widget: string }
      - { label: Description, name: description, widget: string }
      - label: Hero Background Image
        name: heroBackground
        widget: image
        required: false
        media_library:
          config:
            multiple: false
